# Generated by Django 2.1.1 on 2019-11-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191122_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shop.Payment'),
            preserve_default=False,
        ),
    ]
