# Generated by Django 2.1.1 on 2019-11-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191122_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='shop.Seller'),
            preserve_default=False,
        ),
    ]
